import React, { useState, useEffect } from "react"
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../../styles/Home.module.css'
import customers from '../../../styles/Klanten.module.css'
import add from '../../../styles/Add.module.css'

import { GraphQLClient } from 'graphql-request'
import { faPlus, faTimes } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

const graph = new GraphQLClient(
  "https://godefroy-api.herokuapp.com/"
);

function Fotodetail({ customer }) {

  const [admin, setAdmin] = useState();
  useEffect(() => {
    const admin = localStorage.getItem('admin', admin);
    setAdmin(admin);
  }, [admin]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Godefroy Bandenhotel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.navigation}>
          <div className={styles.logo}>
            <Image src="/godefroy.svg" width='185px' height='55px' />
          </div>
          <div className={styles.links}>
            <a href="/"><p className={styles.link_item}>Overzicht</p></a>
            <a href="/klanten"><p className={styles["link_item"] + " " + styles["active"]}>Klanten</p></a>
            {admin ?
              <a href="/logout"><p className={styles.link_item}>Logout</p></a>
              : ''}
          </div>
        </div>
        <div className={customers.dashboard}>
          <form>
            <div className={customers.header}>
              <div>
                <input className={add.name} value={customer.name} />
                <input className={add.name} type="text" placeholder="link afbeelding" />
              </div>
              <button className={add.submit} type="submit">Upload</button>
            </div>
            <div className={add.imagebox}>
              <div className={add.viewimage}>
                <img src="/test.jpg" />
                <div className={add.viewimage_date}>
                  <p>30-05-2021</p>
                </div>
                {admin ?
                  <div className={add.viewimage_delete}>
                    <FontAwesomeIcon icon={faTimes} />
                  </div>
                  : ''}
              </div>
            </div>
          </form>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>© 2021 - Garage Godefroy x Jaxxpected</p>
      </footer>
    </div>
  );
}

export default Fotodetail

export async function getStaticProps({ params }) {
  const { customer } = await graph.request(
    `
    query Customer($id: ID!) {
      customer(id: $id) {
        id
        name
        plate
        atelier
        lang
        email
      }
    }
    `, {
    id: params.id
  }
  )
  return {
    props: {
      customer
    }
  }
}

export async function getStaticPaths() {
  const { customers } = await graph.request(
    `
    {
      customers {
        id
      }
    }
    `
  )
  return {
    paths: customers.map(({ id }) => ({
      params: { id }
    })),
    fallback: false
  }
}