import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import auth from '../styles/Auth.module.css'

export default function Auth() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Godefroy Bandenhotel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={auth.field}>
          <div className={auth.quote}>
            <p className={styles.dashboard_slogan}>Collect the wheels and control your garage online</p>
            <Image src="/slogan.svg" width='350px' height='350px' />
          </div>
          <div className={auth.authentication}>
            <form className={auth.login}>
              <label className={auth.auth_label}>Naam</label>
              <input className={auth.auth_name} placeholder="VUL HIER UW NAAM IN" required />
              <div className={auth.auth_line}></div>
              <label className={auth.auth_label}>Wachtwoord</label>
              <input className={auth.auth_name} placeholder="VUL HIER UW WACHTWOORD IN" type="password" required />
              <div className={auth.auth_line}></div>
              <button className={auth.auth_submit} type="submit">Login</button>
            </form>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>© 2021 - Garage Godefroy x Jaxxpected</p>
      </footer>
    </div>
  )
}
