import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import data from '../data/costumerList.json'
import styles from '../styles/Home.module.css'
import costumers from '../styles/Klanten.module.css'

function Klanten() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Godefroy Bandenhotel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/5c912fe029.js" crossorigin="anonymous"></script>
      </Head>

      <main className={styles.main}>
        <div className={styles.navigation}>
          <div className={styles.logo}>
            <Image src="/godefroy.svg" width='185px' height='55px' />
          </div>
          <div className={styles.links}>
            <p className={styles.link_item}><Link href="/">Overzicht</Link></p>
            <p className={styles.link_item}><Link href="/klanten">Klanten</Link></p>
            <p className={styles.link_item}><Link href="/mail">Mail</Link></p>
          </div>
        </div>
        <div className={costumers.dashboard}>
          <div className={costumers.header}>
            <h1>Klantenlijst</h1>
            <div>
              <a href='/toevoegen' className={costumers.header_add}><i className="fas fa-plus"></i></a>
              <div className={costumers.header_search}>
                <p>Search</p>
                {/* Here comes input field */}
              </div>
            </div>
          </div>
          <div className={costumers.clients}>
            <div className={costumers.filter}>
              <p className={costumers.filter_name}>Naam</p>
              <p className={costumers.filter_plate}>Nummerplaat</p>
              <p className={costumers.filter_lang}>Taal</p>
              <p className={costumers.filter_atelier}>Plaats</p>
              <p className={costumers.filter_email}>E-mail</p>
            </div>
            {data.users.map(user => (
              <div className={costumers.client}>
                <p className={costumers.client_name}>{user.name}</p>
                <p className={costumers.client_plate}>1VEF257</p>
                <p className={costumers.lang}>{user.lang}</p>
                <p className={costumers.atelier}>F1</p>
                <p className={costumers.email}>johndoe@gmail.com</p>
              </div>
            ))}
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>© 2021 - Garage Godefroy x Jaxxpected</p>
      </footer>
    </div>
  )
}

export default Klanten