import { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import costumers from '../styles/Klanten.module.css'

import { firestore } from "../utils/firebase"

function Klanten() {

  const [users, setUsers] = useState([])

  useEffect(() => {
    const fetchData = async () => {
      const data = await firestore.collection("costumer").get();
      setUsers(data.docs.map(doc => doc.data()))
    }
    fetchData()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Godefroy Bandenhotel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/5c912fe029.js" crossOrigin="anonymous"></script>
      </Head>

      <main className={styles.main}>
        <div className={styles.navigation}>
          <div className={styles.logo}>
            <Image src="/godefroy.svg" width='185px' height='55px' />
          </div>
          <div className={styles.links}>
            <p className={styles.link_item}><Link href="/">Overzicht</Link></p>
            <p className={styles.link_item}><Link href="/klanten">Klanten</Link></p>
            <p className={styles.link_item}><Link href="/mail">Mail</Link></p>
          </div>
        </div>
        <div className={costumers.dashboard}>
          <div className={costumers.header}>
            <h1>Klantenlijst</h1>
            <div>
              <a href='/toevoegen' className={costumers.header_add}><i className="fas fa-plus"></i></a>
              <div className={costumers.header_search}>
                <p>Search</p>
                {/* Here comes input field */}
              </div>
            </div>
          </div>
          <div className={costumers.clients}>
            <div className={costumers.filter}>
              <p className={costumers.filter_name}>Naam</p>
              <p className={costumers.filter_plate}>Nummerplaat</p>
              <p className={costumers.filter_lang}>Taal</p>
              <p className={costumers.filter_atelier}>Plaats</p>
              <p className={costumers.filter_email}>E-mail</p>
            </div>
            {users.map(user => (
              <div key="" className={costumers.client}>
                <p className={costumers.client_name}>{user.Name}</p>
                <p className={costumers.client_plate}>{user.Plate}</p>
                <p className={costumers.lang}>{user.Lang}</p>
                <p className={costumers.atelier}>{user.Atelier}</p>
                <p className={costumers.email}>{user.Email}</p>
              </div>
            ))}
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>© 2021 - Garage Godefroy x Jaxxpected</p>
      </footer>
    </div>
  )
}

export default Klanten