import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import auth from '../styles/Auth.module.css'

import { gql, useLazyQuery } from "@apollo/client";
import { useState, useEffect } from "react";

const LOGIN = gql`
  query login($email: String, $password: String){
    login(user: { email: $email, password: $password}){
      token
    }
  }
`;

function Login() {

  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [login, { data }] = useLazyQuery(LOGIN);

  useEffect(() => {
    if (data) { localStorage.setItem('token', data.login.token) }
  }, [data]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Godefroy Bandenhotel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={auth.field}>
          <div className={auth.quote}>
            <p className={styles.dashboard_slogan}>Collect the wheels and control your garage online</p>
            <Image src="/slogan.svg" width='350px' height='350px' />
          </div>
          <div className={auth.authentication}>
            <form className={auth.login} onSubmit={e => {
              e.preventDefault();
              login({ variables: { email: email, password: password } });
            }}>
              <label className={auth.auth_label}>E-mail</label>
              <input className={auth.auth_name} placeholder="VUL HIER UW E-MAIL IN" onChange={e => setEmail(e.target.value)} required />
              <div className={auth.auth_line}></div>
              <label className={auth.auth_label}>Wachtwoord</label>
              <input className={auth.auth_name} placeholder="VUL HIER UW WACHTWOORD IN" onChange={e => setPassword(e.target.value)} type="password" required />
              <div className={auth.auth_line}></div>
              <button className={auth.auth_submit} type="submit"><a href="/admin">Login</a></button>
            </form>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>© 2021 - Garage Godefroy x Jaxxpected</p>
      </footer>
    </div>
  )
}

export default Login