import { useState, useEffect } from "react";
import Head from 'next/head'
import Image from 'next/image'
import InputMask from "react-input-mask";
import { gql, useMutation } from '@apollo/client';

import styles from '../styles/Home.module.css'
import customers from '../styles/Klanten.module.css'
import add from '../styles/Add.module.css'

const CREATE = gql`
  mutation addCustomer($name: String!, $plate: String!, $atelier: String!, $lang: String!, $email: String!, $remark: String!, $wra: String!){
    addCustomer(customer: { 
      name: $name, 
      plate: $plate, 
      atelier: $atelier, 
      lang: $lang, 
      email: $email, 
      remark: $remark,
      slv: $slv,
      sla: $sla,
      srv: $srv,
      sra: $sra,
      wlv: $wlv,
      wla: $wla,
      wrv: $wrv,
      wra: $wra
      }){
      id
    }
  }
`;

function Toevoegen() {

  const [name, setName] = useState('');
  const [plate, setPlate] = useState('');
  const [atelier, setAtelier] = useState('');
  const [lang, setLang] = useState('');
  const [email, setEmail] = useState('');
  const [remark, setRemark] = useState('');
  const [slv, setSlv] = useState('')
  const [sla, setSla] = useState('')
  const [srv, setSrv] = useState('')
  const [sra, setSra] = useState('')
  const [wlv, setWlv] = useState('')
  const [wla, setWla] = useState('')
  const [wrv, setWrv] = useState('')
  const [wra, setWra] = useState('')

  const [create, { data }] = useMutation(CREATE);
  useEffect(() => {
    if (data) { console.log(data); }
  }, [data]);

  const [showSummer, setSummer] = useState("false");
  const handleToggle = () => {
    setSummer(!showSummer);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Godefroy Bandenhotel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.navigation}>
          <div className={styles.logo}>
            <Image src="/godefroy.svg" width='185px' height='55px' />
          </div>
          <div className={styles.links}>
            <a href="/"><p className={styles.link_item}>Overzicht</p></a>
            <a href="/klanten"><p className={styles["link_item"] + " " + styles["active"]}>Klanten</p></a>
          </div>
        </div>
        <div className={customers.dashboard}>
          <form onSubmit={e => {
            e.preventDefault();
            create({ variables: { name: name, plate: plate, atelier: atelier, lang: lang, email: email, remark: remark, slv: slv, sla: sla, srv: srv, sra: sra, wlv: wlv, wla: wla, wrv: wrv, wra: wra } });
          }}>
            <div className={customers.header}>
              <input className={add.name} placeholder="Naam" onChange={e => setName(e.target.value)} />
              <button className={add.submit} type="submit">Opslaan</button>
            </div>
            <div className={add.box}>
              <div className={add.box_small}>
                <label className={add.box_small_label}>Nummerplaat</label>
                <input className={add.box_small_input} placeholder="X-XXX-XXX" onChange={e => setPlate(e.target.value)} />
              </div>
              <div className={add.box_small}>
                <label className={add.box_small_label}>Ligging</label>
                <InputMask className={add.box_small_input} mask="a9-a9" placeholder="XX-XX" onChange={e => setAtelier(e.target.value)} />
              </div>
              <div className={add.box_medium}>
                <label className={add.box_small_label}>Taal</label>
                <input className={add.box_small_input} placeholder="Taal" onChange={e => setLang(e.target.value)} />
              </div>
              <div className={add.box_medium}>
                <label className={add.box_small_label}>E-mail</label>
                <input className={add.box_small_input} placeholder="x@gmail.com" onChange={e => setEmail(e.target.value)} />
              </div>
              <div className={add.box_full}>
                <div className={add.box_full_menu}>
                  <p className={showSummer ? "" : add.box_full_menu_active} onClick={handleToggle}>Zomer</p>
                  <p className={showSummer ? add.box_full_menu_active : ""} onClick={handleToggle}>Winter</p>
                </div>

                <div className={showSummer ? add.hidden : add.box_full_content}>
                  <div className={add.box_full_content_checkbox}>
                    <label className={add.box_small_label}>Profielen</label>
                    <div className={add.box_full_content_options}>
                      <div className={add.box_full_content_checklist}>
                        <label className={add.box_small_checklist_label}>LV</label>
                        <InputMask className={add.box_small_checklist_tire} mask="9,9" type="text" id="lv" name="lv" placeholder="x,x" onChange={e => setSlv(e.target.value)} />
                        <input className={add.checkbox} type="checkbox" id="lv" name="lv" value="lv"></input>

                        <label className={add.box_small_checklist_label}>RV</label>
                        <InputMask className={add.box_small_checklist_tire} mask="9,9" type="text" id="rv" name="rv" placeholder="x,x" onChange={e => setSrv(e.target.value)} />
                        <input className={add.checkbox} type="checkbox" id="rv" name="rv" value="rv"></input>

                        <label className={add.box_small_checklist_label}>LA</label>
                        <InputMask className={add.box_small_checklist_tire} mask="9,9" type="text" id="la" name="la" placeholder="x,x" onChange={e => setSla(e.target.value)} />
                        <input className={add.checkbox} type="checkbox" id="la" name="la" value="la"></input>

                        <label className={add.box_small_checklist_label}>RA</label>
                        <InputMask className={add.box_small_checklist_tire} mask="9,9" type="text" id="ra" name="ra" placeholder="x,x" onChange={e => setSra(e.target.value)} />
                        <input className={add.checkbox} type="checkbox" id="ra" name="ra" value="ra"></input>
                      </div>
                    </div>
                  </div>
                  <div className={add.box_full_content_image}>
                    <Image src="/car.svg" width='300px' height='370px' />
                  </div>
                </div>

                <div className={showSummer ? add.box_full_content : add.hidden}>
                  <div className={add.box_full_content_checkbox}>
                    <label className={add.box_small_label}>Profielen</label>
                    <div className={add.box_full_content_options}>
                      <div className={add.box_full_content_checklist}>
                        <label className={add.box_small_checklist_label}>LV</label>
                        <InputMask className={add.box_small_checklist_tire} mask="9,9" type="text" id="lv" name="lv" placeholder="x,x" onChange={e => setWlv(e.target.value)} />
                        <input className={add.checkbox} type="checkbox" id="lv" name="lv" value="lv"></input>

                        <label className={add.box_small_checklist_label}>RV</label>
                        <InputMask className={add.box_small_checklist_tire} mask="9,9" type="text" id="rv" name="rv" placeholder="x,x" onChange={e => setWrv(e.target.value)} />
                        <input className={add.checkbox} type="checkbox" id="rv" name="rv" value="rv"></input>

                        <label className={add.box_small_checklist_label}>LA</label>
                        <InputMask className={add.box_small_checklist_tire} mask="9,9" type="text" id="la" name="la" placeholder="x,x" onChange={e => setWla(e.target.value)} />
                        <input className={add.checkbox} type="checkbox" id="la" name="la" value="la"></input>

                        <label className={add.box_small_checklist_label}>RA</label>
                        <InputMask className={add.box_small_checklist_tire} mask="9,9" type="text" id="ra" name="ra" placeholder="x,x" onChange={e => setWra(e.target.value)} />
                        <input className={add.checkbox} type="checkbox" id="ra" name="ra" value="ra"></input>
                      </div>
                    </div>
                  </div>
                  <div className={add.box_full_content_image}>
                    <Image src="/car.svg" width='300px' height='370px' />
                  </div>
                </div>

              </div>
              <div className={add.box_mediumplus}>
                <label className={add.box_small_label}>Opmerkingen:</label>
                <textarea placeholder="Typ hier uw opmerking" onChange={e => setRemark(e.target.value)} />
              </div>
              <div className={add.box_small}>
                <label className={add.box_small_label}>Banden</label>
                <div className={add.box_small_checklist}>
                  <label className={add.box_small_checklist_label}>Winter</label>
                  <input className={add.checkbox} type="checkbox" id="winter" name="winter" value="winter"></input>
                  <label className={add.box_small_checklist_label}>Zomer</label>
                  <input className={add.checkbox} type="checkbox" id="summer" name="summer" value="summer"></input>
                </div>
              </div>
              <div className={add.box_small}>
                <p>Kit of band</p>
                <div className={add.box_small_checklist}>
                  <label className={add.box_small_checklist_label}>Kit</label>
                  <input className={add.checkbox} type="checkbox" id="kit" name="kit" value="kit"></input>
                  <label className={add.box_small_checklist_label}>Band</label>
                  <input className={add.checkbox} type="checkbox" id="band" name="band" value="band"></input>
                </div>
              </div>
            </div>
          </form>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>© 2021 - Garage Godefroy x Jaxxpected</p>
      </footer>
    </div>
  )
}

export default Toevoegen